docs/UserGuide.md
Updated add feature in User Guide
=> Update UserGuide to contain add feature with optional tag

src/main/java/seedu/address/logic/commands/DeleteTagCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteTagCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/model/tag/UniqueTagList.java, src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/DeleteTagCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/person/UniquePersonListTest.java, src/test/java/seedu/address/model/tag/UniqueTagListTest.java
Implemented delete a tag feature as well as its tests.
=> Delete a tag

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddEventCommand.java, src/main/java/seedu/address/logic/parser/AddEventCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ReadOnlyAddressBook.java, src/main/java/seedu/address/model/ReadOnlyUserPrefs.java, src/main/java/seedu/address/model/UserPrefs.java, src/main/java/seedu/address/model/event/Event.java, src/main/java/seedu/address/model/event/EventAddress.java, src/main/java/seedu/address/model/event/EventDate.java, src/main/java/seedu/address/model/event/EventName.java, src/main/java/seedu/address/model/event/UniqueEventList.java, src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java, src/main/java/seedu/address/model/event/exceptions/EventNotFoundException.java, src/main/java/seedu/address/storage/JsonAdaptedEvent.java, src/main/java/seedu/address/storage/JsonSerializableAddressBook.java, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/AddTagCommandTest.java, src/test/java/seedu/address/logic/commands/DeleteTagCommandTest.java, src/test/java/seedu/address/model/AddressBookTest.java
This PR is to merge my add event command functionality into the main branch
Key notes
- Create an event with name, date and address with the ability for contacts to be tagged to an event object
- Date should be a date not before today (today or after) and be in format YYYY-MM-DD, to confirm to reminder feature in future milestones
=> Add event command

src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/model/person/UniquePersonList.java, src/main/java/seedu/address/ui/EventContactDisplay.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/EventContactDisplay.fxml, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PersonListPanel.fxml, src/main/resources/view/TagListPanel.fxml
Updated delete_tag command to properly delete tags from contact list as well.
To do:
- Replace placeholder for events list with actual events list (after view events command)
=> Update UI with placeholder for events list

build.gradle, docs/UserGuide.md
Update UG to contain description of the select event command
=> Update UG for select event command

src/main/java/seedu/address/logic/Logic.java, src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/logic/commands/ClearCommand.java, src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/ExitCommand.java, src/main/java/seedu/address/logic/commands/HelpCommand.java, src/main/java/seedu/address/logic/commands/HomeCommand.java, src/main/java/seedu/address/logic/commands/event/SelectEventCommand.java, src/main/java/seedu/address/logic/commands/tag/AddTagCommand.java, src/main/java/seedu/address/logic/commands/tag/DeleteTagCommand.java, src/main/java/seedu/address/logic/commands/tag/ViewTagsCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/ui/EventContactDisplay.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/ResultDisplay.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/HomeCommandTest.java, src/test/java/seedu/address/logic/commands/person/AddCommandTest.java, src/test/java/seedu/address/logic/commands/tag/AddTagCommandTest.java, src/test/java/seedu/address/logic/commands/tag/DeleteTagCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java
Home command is successfully implemented. Will add test cases in the future.
KIV:
If there is time and if it is possible at all, I will try to implement a clickable home button on top of the command `home`.
=> Implement home command

docs/UserGuide.md
Now the command summary is grouped by contact, then tag, then event. Each command is sorted lexicographically within the group.
=> Update UG to include view event and home command

docs/DeveloperGuide.md, docs/UserGuide.md
Updated add_tag notes.
Fixed typo in delete_tag notes.
Added delete_event and add_task features.
=> Update UG and DG to include delete_event and add_task

src/main/java/seedu/address/logic/commands/event/AddEventCommand.java, src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java, src/main/java/seedu/address/model/date/Date.java, src/main/java/seedu/address/model/tag/Tag.java, src/test/java/seedu/address/storage/JsonAdaptedTaskTest.java
Previously, when event/task past deadline, parseDate will flag error and addressbook will be empty. BeforeToday validation is done only during Command now and issue is fixed
=> Fix addressbook.json not loading

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java, src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java, src/main/java/seedu/address/logic/commands/task/MarkCommand.java, src/main/java/seedu/address/logic/commands/task/UnmarkCommand.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/task/AddTaskCommandParser.java, src/main/java/seedu/address/logic/parser/task/DeleteTaskCommandParser.java, src/main/java/seedu/address/logic/parser/task/MarkCommandParser.java, src/main/java/seedu/address/logic/parser/task/UnmarkCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/task/UniqueTaskList.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/logic/parser/task/AddTaskCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/task/UniqueTaskListTest.java
Implemented method to delete associated tasks in events when events are deleted.
Implemented method to throw error when more than 1 space is entered in input.
Update task_description prefix from n/ to td/
=> Fix delete event issues

src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/task/MarkTaskCommand.java, src/main/java/seedu/address/logic/commands/task/UnmarkTaskCommand.java, src/main/java/seedu/address/logic/parser/JobFestGoParser.java, src/main/java/seedu/address/logic/parser/task/MarkCommandParser.java, src/main/java/seedu/address/logic/parser/task/UnmarkCommandParser.java
Unmark to unmark_task and mark to mark_task
=> Change task commands

src/main/java/seedu/address/logic/commands/CommandResult.java, src/main/java/seedu/address/logic/commands/contact/AddContactCommand.java, src/main/java/seedu/address/logic/commands/contact/DeleteContactCommand.java, src/main/java/seedu/address/logic/commands/contact/EditContactCommand.java, src/main/java/seedu/address/logic/commands/contact/FindContactCommand.java, src/main/java/seedu/address/logic/commands/event/AddEventCommand.java, src/main/java/seedu/address/logic/commands/event/DeleteEventCommand.java, src/main/java/seedu/address/logic/commands/event/LinkCommand.java, src/main/java/seedu/address/logic/commands/event/SelectEventCommand.java, src/main/java/seedu/address/logic/commands/tag/AddTagCommand.java, src/main/java/seedu/address/logic/commands/tag/DeleteTagCommand.java, src/main/java/seedu/address/logic/commands/tag/FilterByTagCommand.java, src/main/java/seedu/address/logic/commands/task/AddTaskCommand.java, src/main/java/seedu/address/logic/commands/task/DeleteTaskCommand.java, src/main/java/seedu/address/logic/commands/task/MarkTaskCommand.java, src/main/java/seedu/address/logic/commands/task/UnmarkTaskCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/test/java/seedu/address/logic/commands/contact/AddContactCommandTest.java, src/test/java/seedu/address/logic/commands/contact/DeleteContactCommandTest.java, src/test/java/seedu/address/logic/commands/event/AddEventCommandTest.java, src/test/java/seedu/address/logic/commands/tag/AddTagCommandTest.java, src/test/java/seedu/address/logic/commands/tag/DeleteTagCommandTest.java, src/test/java/seedu/address/logic/commands/task/AddTaskCommandTest.java
Reverts AY2324S1-CS2103T-T09-1/tp#153
=> Revert "Fix UI display upon executing different commands"

src/main/java/seedu/address/logic/commands/task/MarkTaskCommand.java, src/main/java/seedu/address/logic/commands/task/UnmarkTaskCommand.java, src/main/java/seedu/address/model/JobFestGo.java, src/main/java/seedu/address/model/task/exceptions/TaskIsCompletedException.java, src/main/java/seedu/address/model/task/exceptions/TaskNotCompletedException.java, src/main/java/seedu/address/model/task/exceptions/TaskNotFoundException.java
Update mark and unmark command to throw errors when the task is already marked/unmarked.
=> Update mark and unmark command

src/main/java/seedu/address/logic/commands/contact/EditContactCommand.java, src/main/java/seedu/address/model/JobFestGo.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/contact/UniqueContactList.java, src/test/java/seedu/address/logic/commands/contact/AddContactCommandTest.java, src/test/java/seedu/address/logic/commands/event/AddEventCommandTest.java, src/test/java/seedu/address/logic/commands/tag/AddTagCommandTest.java, src/test/java/seedu/address/logic/commands/tag/DeleteTagCommandTest.java, src/test/java/seedu/address/logic/commands/task/AddTaskCommandTest.java
To prevent cases in which contacts are edited to have the same name or same phone number
=> Fix edit command

docs/DeveloperGuide.md, docs/diagrams/ModelClassDiagram.puml, docs/diagrams/StorageClassDiagram.puml, docs/diagrams/UiClassDiagram.puml
Updated the following diagrams:
1. ModelClassDiagram.puml
1. StorageClassDiagram.puml
1. UiClassDiagram.puml
=> Update relevant diagrams of DG

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/event/UniqueEventListTest.java
Rename test cases to match the actual method name `parseTaskDescription` and increase codecov
=> Provide comprehensive testing for existing test cases

src/test/java/seedu/address/logic/commands/CommandResultTest.java, src/test/java/seedu/address/logic/commands/contact/EditContactCommandTest.java, src/test/java/seedu/address/logic/commands/contact/FindContactCommandTest.java, src/test/java/seedu/address/logic/commands/tag/FilterByTagCommandTest.java, src/test/java/seedu/address/model/date/DateTest.java, src/test/java/seedu/address/model/task/TaskTest.java
Update some variable names, some methods that don't follow test case convention and add some test cases to increase Codecov.
=> Refactor old code and add some test cases

docs/diagrams/SelectEventSequenceDiagram.puml
=> Update Select Event Sequence Diagram

src/main/java/seedu/address/storage/JsonJobFestGoStorage.java, src/main/java/seedu/address/storage/JsonSerializableJobFestGo.java
EventNotFoundException not handled in the case event name in task list is invalid.
=> Fix bug that app cannot be opened if file is corrupted

src/main/java/seedu/address/model/contact/UniqueContactList.java, src/test/java/seedu/address/model/contact/UniqueContactListTest.java
-just a test to see if this increases codecov
=> Add test case

docs/UserGuide.md, docs/team/rionshocker.md
- Line break before line 83
- Fix broken TOC links for upcoming features
=> Fix certain nits in UG

docs/DeveloperGuide.md
added the case when name is not alphanumeric
=> Fix Use case for DG

docs/DeveloperGuide.md, docs/diagrams/AddEventSequenceDiagram.puml, docs/diagrams/AddTagSequenceDiagram.puml, docs/diagrams/SelectEventSequenceDiagram.puml
Fix punctuation and line breaks in DG.
Update sequence diagrams.
=> Fix nits in DG
